4415 Refactor Calendar blocking
THIS-Institute/thiscovery-interviews pull request #39
Opened 2022-05-12 20:05 UTC by sophiemachin

2022-05-13 15:47 UTC, afs25 requested changes
See comments

2022-05-13 15:47 UTC, afs25 commented on src/main.py
> +        Put an item into a DynamoDB table
Docstring a bit too generic? How about "Put an item into the self.blocks_table DynamoDB table"?

2022-05-13 15:47 UTC, afs25 commented on src/main.py
> +        Delete an item from a DynamoDB table
Ditto

2022-05-13 15:47 UTC, afs25 commented on src/main.py
> +        self.logger.debug("Calendars to block", extra={"calendars": calendars_acuity})
This is misleading. "Calendars to block" are now calendars_acuity minus do_not_block_calendar_ids because not all calendars_acuity will be blocked. How about:

self.logger.debug("Calendar lists", extra={"calendars_acuity": calendars_acuity, "do_not_block_calendar_ids": do_not_block_calendar_ids})

2022-05-13 15:47 UTC, afs25 commented on tests/test_data.py
> +        "wilma@gmail.com",
I know this is arbritrary, but it is very likely that it is someone's real email address. To comply with GDPR, etc, let's change the domain to email.co.uk

2022-05-13 15:47 UTC, afs25 commented on tests/unit_tests/test_main.py
> +        if test_cal_db is None:
We can use update_allowed=True when calling the put_item method of ddb_client instead of these lines of code.

2022-05-13 15:47 UTC, afs25 commented on tests/unit_tests/test_main.py
> +        )
The signature of unittest.assertEqual is unittest.assertEqual(expected, actual) so this should be the other way around. Same thing for other usages.

2022-05-13 15:47 UTC, afs25 commented on tests/unit_tests/test_main.py
> +            delete_response["ResponseMetadata"]["HTTPStatusCode"], HTTPStatus.OK
Invert arguments

2022-05-13 15:47 UTC, afs25 commented on tests/unit_tests/test_main.py
> +        self.assertEqual(None, block)
Better to use self.assertIsNone here?

2022-05-13 15:47 UTC, afs25 commented on tests/unit_tests/test_main.py
> +        self.calendar_blocker.delete_blocks()
This cleanup will never happen if the test fails at the assertion point. If it is important that it happens, move to tearDownClass

2022-05-13 18:02 UTC, sophiemachin commented on tests/unit_tests/test_main.py
> +        if test_cal_db is None:
I actually missed a setUpClass for TestAcuityEvent, so I've made the change and duplicated it there

2022-05-16 08:24 UTC, sophiemachin commented on tests/unit_tests/test_main.py
> +        self.calendar_blocker.delete_blocks()
I've moved the `delete_blocks` but now I'm wondering if we should have a separate test for this?

2022-05-16 08:48 UTC, afs25 commented on tests/unit_tests/test_main.py
> +        cls.calendar_blocker.delete_blocks()
Let's move this up (before actual tests)

2022-05-16 08:48 UTC, afs25 commented on tests/unit_tests/test_main.py
> +        self.calendar_blocker.delete_blocks()
Let's discuss this in a call

2022-05-16 11:53 UTC, merged